### ISSUE TITLE
Attachment Component

### ISSUE THREAD

**Issue by renatonascalves** [wp-graphql/wp-graphql-buddypress#3]
BuddyPress uses an internal attachment system for adding avatar and cover images to users, blogs and groups (or other custom components).

- [x] Field(s)
  - [x] Add avatar and cover fields to the `User` type. See #6 
  - [x] Add avatar and cover fields to the `Group` type. See #2 
  - [x] Add avatar and cover fields to the `Blog` type. See #16
- [x] Type(s)
  - [x] Attachment
- [x] Mutation (for the Group/Blog/User types)
  - [x] Create, aka, Upload
  - [x] Delete
- [x] Unit tests

****

Some prior art on image upload: https://github.com/hughdevore/wp-graphql-file-upload
Seems to be a good spec to follow: https://github.com/jaydenseric/graphql-multipart-request-spec
