### ISSUE TITLE
Members Component

### ISSUE THREAD

**Issue by renatonascalves** [wp-graphql/wp-graphql-buddypress#6]
Add basic support to the Members component:

- [x] Field(s)
-- Add BuddyPress fields to the `User` type (see #8)
-- XProfile fields (see #10)
-- Avatar (see #3)
- [x] Connections
  - [x] RootQuery -> members (see #9)
  - [x] groups -> members (see #2)
  - [x] User -> xprofile groups -> group fields (see #10)
- [x] Enums
 - MemberOrderByTypeEnum
 - MemberTypesEnum
- [x] Unit tests
- [x] Check pagination
- [x] Mutation(s) (Pending: https://github.com/wp-graphql/wp-graphql/issues/143)
  - [x] ~update (we don't have anything to update)~
  - [x] delete
  - [x] ~create (users don't create account, per se)~
